name: Larastan Static Analysis
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        operating-system:
          - ubuntu-22.04
        php-version:
          - '8.3'
    name: php ${{ matrix.php-version }} on ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
      - name: Install Composer Dependencies
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Run Larastan
        run: ./vendor/bin/phpstan analyse -vvv --memory-limit=2G
      - name: Cache PHPStan Cache Directory
        uses: actions/cache@v4
        with:
          path: cache/phpstan
          key: "phpstan-cache-${{ github.run_id }}"
          restore-keys: |
              phpstan-cache-
