name: Laravel Pint
on: [push, pull_request]
jobs:
  phplint:
    strategy:
      matrix:
        operating-system:
          - ubuntu-22.04
        php-version:
          - '8.3'
    name: php ${{ matrix.php-version }} on ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
      - name: Install Composer Dependencies
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Run Pint
        run: ./vendor/bin/pint -vvv
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: pint linter'
          commit_user_name: HDVinnie
          commit_user_email: hdinnovations@protonmail.com
          commit_author: HDVinnie <hdinnovations@protonmail.com>