name: Pest Type Coverage
on: [push, pull_request]
jobs:
  tests:
    strategy:
      fail-fast: true
      matrix:
        operating-system:
          - ubuntu-22.04
        php-version:
          - '8.3'
    name: php ${{ matrix.php-version }} on ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: pcov
          tools: composer:v2
      - name: Install Composer Dependencies
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --optimize-autoloader
      - name: Run Pest Type Coverage
        run: ./vendor/bin/pest --type-coverage
